### ISSUE TITLE
Disagreements between Makefiles and filename case, e.g. gnu c++

### ISSUE THREAD

**Issue by ernie-cordell** [TomSwan/collections#1]
I checked the Vapp chapter in gnuc++ and the Makefile was looking for lower case but the filenames were all uppercase.  Since I'm a GNU guy, that's a critical difference.  While I understand some people may have some library problems, I'll cross that bridge if I can get to it.

**Comment by TomSwan** [comment]
I'm working on revised listings that compile; the listings were correct at publication time but you are correct that some changes such as case and some other minor issues have caused trouble since then and need updating to compile now. 
  
  
   On November 15, 2019 at 8:33 PM Ernie Cordell <notifications@github.com> wrote: 
    
   
   I checked the Vapp chapter in gnuc++ and the Makefile was looking for lower case but the filenames were all uppercase. Since I'm a GNU guy, that's a critical difference. While I understand some people may have some library problems, I'll cross that bridge if I can get to it.
   —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
  
  
    
  
  
   http://www.tomswan.com

**Comment by ernie-cordell** [comment]
Thank ya, thank ya vurry much.
